### ISSUE TITLE
[iOS] En tant qu'emprunteur, je peux faire une demander de prêt

### ISSUE THREAD

**Issue by VictorLuc4** [HETIC-W3-G12/iOS-Application#7]
## Description générale

Investissement sur un projet.

## Process d'investissement

Process décris sur ce lien : https://github.com/HETIC-W3-G12/iOS-Application/issues/4

## Pré-requis
* @Abelia 
    - [x] Besoin Maquettes
* @MRWS @samchery 
lien : https://github.com/HETIC-W3-G12/node-api/issues/11
    - [x] API : creation de projet
* Depuis Master

## Todo Liste

- [x] ViewController Menu
- [x] ViewController Creation Projet
- [x] Passer la projectsliste en root apres connexion
- [x] API Request
- [x] Request Handling
- [x] Gérer le changement Investisseur/Emprunteur

**Comment by VictorLuc4** [comment]
Creation faite, basics errors handled, little animations added too.
