### ISSUE TITLE
[iOS] En tant qu'investisseur, je peux voir mes investissements en cours

### ISSUE THREAD

**Issue by VictorLuc4** [HETIC-W3-G12/iOS-Application#8]
## Description générale

En tant qu'investisseur, je peux voir mes investissements **en cours**.

## Process d'investissement

Process décris sur ce lien : https://github.com/HETIC-W3-G12/iOS-Application/issues/4

## Pré-requis
* @Abelia 
    - [x] Besoin Maquettes
* @MRWS @samchery 
lien : https://github.com/HETIC-W3-G12/node-api/issues/7
    - [ ] API : Liste des projets financés par un utilisateur
* L'écran Menu

## Todo Liste

- [ ] Un Bouton dans le menu
- [ ] ViewController de la liste
- [ ] Un tableView pour afficher la liste des projets financés
- [ ] ViewController du projet pour vois son avancement
- [ ] Afficher toutes les infos du projet
- [ ] Une progress bar
- [ ] Un tableView (petit) pour voir les échéanches
- [ ] API Request
- [ ] Request Handling

**Comment by VictorLuc4** [comment]
Questions en suspend : 
**Comment je vais afficher la liste des échéances dynamiquement sans que ça fasse top moche ?**
- ScrollView qui englobe un TableView qui as comme hauteur son `nombre de cellule * la hauteur d'une cellule`
- Un label Fixe, qui indique le nombre d'échéances restantes et le nombre de validées ?
